GET http://localhost:8001/member/hello
Accept: application/json

###

GET http://localhost:8000/member/hello
Accept: application/json

###

GET http://localhost:8000/member/member/count
Accept: application/json

###

POST http://localhost:8000/member/member/register?mobile=1234567
Accept: application/json

###